version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Map host port 5000 to container port 5000
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - WORKERS=2
    # If you have a service account file, mount it (optional)
    volumes:
      - ./backend:/app:ro
      - ./service-account-key.json:/service-account-key.json:ro
    # Healthcheck to verify backend responding
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Frontend is optional here; build separately when ready
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - VITE_BACKEND_URL=http://backend:5000

networks:
  default:
    driver: bridge
