import React from 'react';

const InterventionCard = ({ intervention, index }) => {
  return (
    <div className="intervention-card">
      <div className="intervention-title">
        {index + 1}. {intervention.title}
      </div>
      <div className="intervention-desc">
        {intervention.description}
      </div>
      <div className="intervention-details">
        <div className="detail-item">
          <span className="detail-label">Runoff Reduction:</span>
          <span className="detail-value">{intervention.runoff_reduction_pct}%</span>
        </div>
        <div className="detail-item">
          <span className="detail-label">Cost:</span>
          <span className="detail-value">{intervention.cost_bracket}</span>
        </div>
        <div className="detail-item">
          <span className="detail-label">Timeline:</span>
          <span className="detail-value">{intervention.implementation_months} months</span>
        </div>
        <div className="detail-item">
          <span className="detail-label">KPI:</span>
          <span className="detail-value">{intervention.kpi}</span>
        </div>
        {intervention.contact && (
          <div className="detail-item">
            <span className="detail-label">Contact:</span>
            <span className="detail-value">{intervention.contact}</span>
          </div>
        )}
      </div>
    </div>
  );
};

const InterventionsSection = ({ interventions, loading }) => {
  if (!interventions || interventions.length === 0) return null;

  return (
    <div className="section">
      <h3>Recommended Interventions</h3>
      <div style={{
        opacity: loading ? 0.6 : 1,
        transition: 'opacity 0.3s ease'
      }}>
        {loading ? (
          <div className="intervention-card" style={{
            textAlign: 'center',
            padding: '20px',
            background: 'rgba(255, 255, 255, 0.6)',
            border: '1px solid rgba(7, 23, 63, 0.1)',
            borderRadius: '12px',
            color: '#0042A6',
            fontFamily: 'Overpass, sans-serif',
            fontWeight: '600'
          }}>
            Generating AI-powered recommendations...
          </div>
        ) : (
          <div className="interventions-list">
            {interventions.map((intervention, index) => (
              <InterventionCard
                key={index}
                intervention={intervention}
                index={index}
              />
            ))}
          </div>
        )}
      </div>
      
      {!loading && interventions.length > 0 && (
        <div style={{
          fontSize: '12px',
          color: '#0042A6',
          textAlign: 'center',
          marginTop: '16px',
          fontFamily: 'Overpass, sans-serif',
          fontWeight: '600'
        }}>
          Recommendations generated by local AI based on area-specific analysis
        </div>
      )}
    </div>
  );
};

// Add CSS styles for the new detail structure
const styles = `
.detail-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 0;
  border-bottom: 1px solid rgba(7, 23, 63, 0.05);
}

.detail-label {
  font-family: 'Overpass', sans-serif;
  font-size: 12px;
  color: #0042A6;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.detail-value {
  font-family: 'Fira Sans', sans-serif;
  font-size: 13px;
  color: #07173F;
  font-weight: 600;
}

.interventions-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
`;

// Inject styles if not already present
if (typeof document !== 'undefined' && !document.getElementById('interventions-styles')) {
  const styleSheet = document.createElement('style');
  styleSheet.id = 'interventions-styles';
  styleSheet.textContent = styles;
  document.head.appendChild(styleSheet);
}

export default InterventionsSection;