import React, { useState, useEffect } from 'react';
import './IntroPopup.css';

const IntroPopup = ({ onComplete }) => {
  const [currentSlide, setCurrentSlide] = useState(0);
  
  const slides = [
    {
      title: "UrbanAI",
      subtitle: "Climate-Adaptive Digital Twin Platform",
      content: "Real NASA Earth Engine data meets local AI for evidence-based urban planning.",
      pattern: "/patterns/Orbits.png"
    },
    {
      title: "Live Satellite Analysis",
      subtitle: "Six NASA datasets integrated",
      content: "Temperature • Precipitation • Elevation • Soil • Population • Nighttime Lights",
      pattern: "/patterns/Waves.png"
    },
    {
      title: "AI-Powered Insights",
      subtitle: "Local LLM recommendations",
      content: "Context-aware urban planning suggestions generated by advanced language models.",
      pattern: "/patterns/Code.png"
    },
    {
      title: "Ready to Begin?",
      subtitle: "Start your climate analysis",
      content: "Upload your area boundary or use our sample locations to see UrbanAI in action.",
      pattern: "/patterns/Rosette.png"
    }
  ];

  const nextSlide = () => {
    if (currentSlide < slides.length - 1) {
      setCurrentSlide(currentSlide + 1);
    } else {
      onComplete();
    }
  };

  const skipIntro = () => {
    onComplete();
  };

  return (
    <div className="intro-overlay">
      <div className="intro-popup">
        <div className="intro-header">
          <img src="/nasa-logo.svg" alt="NASA Space Apps" className="intro-logo" />
          <button className="intro-skip" onClick={skipIntro} title="Skip to main app">×</button>
        </div>
        
        <div className="intro-content">
          <div className="intro-slide">
            <div className="intro-visual">
              <img 
                src={slides[currentSlide].pattern} 
                alt="" 
                className="intro-pattern" 
              />
            </div>
            <h1 className="intro-title">{slides[currentSlide].title}</h1>
            <p className="intro-subtitle">{slides[currentSlide].subtitle}</p>
            <p className="intro-description">{slides[currentSlide].content}</p>
          </div>
        </div>
        
        <div className="intro-navigation">
          <div className="intro-progress">
            <div 
              className="intro-progress-bar" 
              style={{ width: `${((currentSlide + 1) / slides.length) * 100}%` }}
            />
          </div>
          
          <div className="intro-controls">
            {currentSlide > 0 && (
              <button className="intro-back" onClick={() => setCurrentSlide(currentSlide - 1)}>
                ← Back
              </button>
            )}
            <button className="intro-next" onClick={nextSlide}>
              {currentSlide < slides.length - 1 ? 'Next →' : 'Launch UrbanAI 🚀'}
            </button>
          </div>
        </div>
        
        <div className="intro-footer">
          <span className="intro-badge">NASA Space Apps Challenge 2025</span>
        </div>
      </div>
    </div>
  );
};

export default IntroPopup;